title: EEG101 - Fundamentals of Open & Rigorous EEG Science
email: robert.oostenveld@donders.ru.nl
description: EEG101 COST Action
baseurl: ""
url: https://www.eeg101.eu
logo: /assets/images/logo-v1.png

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation
header_pages:
  - index.md
  - collaborators.md
  - workgroups.md
  - contact.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - STRUCTURE.md
  - LICENSE.md
